USE [master]
GO
/****** Object:  Database [BenhVienDB]    Script Date: 5/12/2026 12:53:05 PM ******/
CREATE DATABASE [BenhVienDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BenhVienDB', FILENAME = N'D:\SQLdata\BenhVienDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BenhVienDB_log', FILENAME = N'D:\SQLdata\BenhVienDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BenhVienDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BenhVienDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BenhVienDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BenhVienDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BenhVienDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BenhVienDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BenhVienDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BenhVienDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BenhVienDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BenhVienDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BenhVienDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BenhVienDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BenhVienDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BenhVienDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BenhVienDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BenhVienDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BenhVienDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BenhVienDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BenhVienDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BenhVienDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BenhVienDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BenhVienDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BenhVienDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BenhVienDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BenhVienDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BenhVienDB] SET  MULTI_USER 
GO
ALTER DATABASE [BenhVienDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BenhVienDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BenhVienDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BenhVienDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BenhVienDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BenhVienDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BenhVienDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [BenhVienDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BenhVienDB]
GO
/****** Object:  Table [dbo].[Consultations]    Script Date: 5/12/2026 12:53:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Consultations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PatientId] [int] NULL,
	[DoctorId] [int] NULL,
	[EcgRecordId] [int] NULL,
	[PatientComplaint] [nvarchar](max) NULL,
	[SubmittedAt] [datetime] NULL,
	[DoctorFindings] [nvarchar](max) NULL,
	[DoctorTreatment] [nvarchar](max) NULL,
	[RespondedAt] [datetime] NULL,
	[Status] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DataBenhNhan]    Script Date: 5/12/2026 12:53:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DataBenhNhan](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[xi] [float] NULL,
	[oi] [float] NULL,
	[qi] [float] NULL,
	[envelope] [float] NULL,
	[pred_peak_mask] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Doctors]    Script Date: 5/12/2026 12:53:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Doctors](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[Specialty] [nvarchar](100) NULL,
	[Username] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EcgRecords]    Script Date: 5/12/2026 12:53:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EcgRecords](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PatientId] [int] NULL,
	[RecordName] [nvarchar](100) NULL,
	[RecordedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Patients]    Script Date: 5/12/2026 12:53:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patients](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[Age] [int] NULL,
	[Gender] [nvarchar](20) NULL,
	[PhoneNumber] [nvarchar](20) NULL,
	[Email] [nvarchar](100) NULL,
	[Address] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[DataBenhNhan] ON 

INSERT [dbo].[DataBenhNhan] ([id], [xi], [oi], [qi], [envelope], [pred_peak_mask]) VALUES (1, NULL, 0.011663549630455572, NULL, NULL, NULL)
INSERT [dbo].[EcgRecords] ([Id], [PatientId], [RecordName], [RecordedAt]) VALUES (15, 1, N'ecg_record_15.json', CAST(N'2024-03-15T08:00:00.000' AS DateTime))
SET IDENTITY_INSERT [dbo].[EcgRecords] OFF
GO
SET IDENTITY_INSERT [dbo].[Patients] ON 

INSERT [dbo].[Patients] ([Id], [FullName], [Age], [Gender], [PhoneNumber], [Email], [Address]) VALUES (1, N'Nguyen Van A', 45, N'Male', N'0901234567', N'nva@example.com', N'123 Le Loi, HCMC')
SET IDENTITY_INSERT [dbo].[Patients] OFF
GO
ALTER TABLE [dbo].[Consultations] ADD  DEFAULT (getdate()) FOR [SubmittedAt]
GO
ALTER TABLE [dbo].[Consultations] ADD  DEFAULT ('Pending') FOR [Status]
GO
ALTER TABLE [dbo].[EcgRecords] ADD  DEFAULT (getdate()) FOR [RecordedAt]
GO
ALTER TABLE [dbo].[Consultations]  WITH CHECK ADD FOREIGN KEY([DoctorId])
REFERENCES [dbo].[Doctors] ([Id])
GO
ALTER TABLE [dbo].[Consultations]  WITH CHECK ADD FOREIGN KEY([EcgRecordId])
REFERENCES [dbo].[EcgRecords] ([Id])
GO
ALTER TABLE [dbo].[Consultations]  WITH CHECK ADD FOREIGN KEY([PatientId])
REFERENCES [dbo].[Patients] ([Id])
GO
ALTER TABLE [dbo].[EcgRecords]  WITH CHECK ADD FOREIGN KEY([PatientId])
REFERENCES [dbo].[Patients] ([Id])
GO
USE [master]
GO
ALTER DATABASE [BenhVienDB] SET  READ_WRITE 
GO
